# Generated by Django 4.0.3 on 2022-03-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MyFormModel',
        ),
    ]
